### ISSUE TITLE
option "follow tail of the log" (put listbox selection always to last item) is needed

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_runner#35]

**Comment by halfbrained** [comment]
I encountered some issues here.

On latest beta: 
* LOG_SET_LINEINDEX - cant figure out how to operate this :)
    ```    python
    >>> app_log(LOG_SET_LINEINDEX, 30, panel=LOG_PANEL_OUTPUT) # - integer index - err
    ERROR: Exception in CudaText: Access violation
    TypeError: app_log() argument 2 must be str, not int
    ...
    >>> app_log(LOG_SET_LINEINDEX, '30', panel=LOG_PANEL_OUTPUT) # - string index - no effect
    ```
* Also unable to to set scroll with `Editor.set_prop` `PROP_LINE_TOP`
    ``` python
    >>> h = app_proc(PROC_GET_OUTPUT_FORM, '')
    >>> edh = dlg_proc(h, DLG_CTL_HANDLE, name='editor')
    >>> oed = Editor(edh)
    >>> oed.set_prop(PROP_LINE_TOP, 30)
    TypeError: an integer is required (got type NoneType)
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/H/cuda/__FM/py/cudatext.py", line 1313, in set_prop
        return ct.ed_set_prop(self.h, id, value)
    SystemError: <built-in function ed_set_prop> returned a result with an error set
    ERROR: Exception in CudaText: SystemError: <built-in function ed_set_prop> returned a result with an error set
    ```

On older version with the 'listbox' Output - having similar problem with LOG_SET_LINEINDEX
``` python
>>> print(app_log(LOG_GET_LINEINDEX, '0', panel=LOG_PANEL_OUTPUT)) # get index - works
0
>>> print(app_log(LOG_SET_LINEINDEX, 20, panel=LOG_PANEL_OUTPUT)) # cant set integer index
ERROR: Exception in CudaText: Access violation
TypeError: app_log() argument 2 must be str, not int
>>> print(app_log(LOG_SET_LINEINDEX, '20', panel=LOG_PANEL_OUTPUT)) # ... or string
None
>>> print(app_log(LOG_GET_LINEINDEX, '0', panel=LOG_PANEL_OUTPUT)) # no effect
0
>>> print(app_log(LOG_SET_LINEINDEX, '', tag=20, panel=LOG_PANEL_OUTPUT)) # just in case - tag
None
>>> print(app_log(LOG_GET_LINEINDEX, '0', panel=LOG_PANEL_OUTPUT)) # also no effect
0
```

**Comment by Alexey-T** [comment]
>app_log(LOG_SET_LINEINDEX, '30', panel=LOG_PANEL_OUTPUT)

fixed! Thanks

>edh = dlg_proc(h, DLG_CTL_HANDLE, name='editor')

name was not set in my code. `edh is None`.
I just set this name to "log".

**Comment by Alexey-T** [comment]
beta updated!
this works
```
        
    def run(self):
        for i in range(50):
            app_log(LOG_ADD,str(i),panel=LOG_PANEL_OUTPUT)
        h = app_proc(PROC_GET_OUTPUT_FORM, '')
        edh = dlg_proc(h, DLG_CTL_HANDLE, name='log')
        oed = Editor(edh)
        oed.set_prop(PROP_LINE_TOP, 30)
```

**Comment by halfbrained** [comment]
Will be using Editor API, but was just looking to see what will happen :) (on latest beta)
``` python
app_log(LOG_SET_LINEINDEX, 10, panel=LOG_PANEL_OUTPUT)
```
- this gives an error:
``` python
TypeError: app_log() argument 2 must be str, not int

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/H/cuda/__FM/py/cudatext.py", line 944, in app_log
    return ct.app_log(id, text, tag, panel)
SystemError: <built-in function app_log> returned a result with an error set
ERROR: Exception in CudaText: SystemError: <built-in function app_log> returned a result with an error set
```
then caret plugins stop working; and when I click in editor  I get a bunch of errors like:
``` python
ERROR: Exception in CudaText for on_caret: Access violation
ERROR: Exception in CudaText for cuda_extended_selection.on_caret: Access violation
ERROR: Exception in CudaText for cuda_hilite_occurrences.on_caret: Access violation
ERROR: Exception in CudaText for cuda_extended_selection.on_caret: Access violation
```
... or CudaText crashes (windows just disappears)

Probably some wiki updating should be done about log panels :)

**Comment by Alexey-T** [comment]
Yes, edited the wiki about 'text' parameter.
you must write

    app_log(LOG_SET_LINEINDEX, '10', panel=LOG_PANEL_OUTPUT)

**Comment by Alexey-T** [comment]
and I cannot repro 'AV" here, even HiliteOccurances works after that.

**Comment by Alexey-T** [comment]
Made fix https://github.com/Alexey-T/CudaText/commit/b26cd0fe8bd655191b330879781f39317df12e42

**Comment by halfbrained** [comment]
added option - "tail_log"

Will try to reproduce AV on the fresh install a bit later

**Comment by halfbrained** [comment]
@Alexey-T , I had 100% reproducible AV issue on fresh install of older beta, but on the latest it's fixed so I'll assume it's fixed and no further investigation is necessary :+1:
